# db_functions.py
"""
Functions to build and work with a database that stores time block objects
"""

from pprint import pprint

d = [{'CRN': '11850',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET211',
  'course_title': 'Environmental Quality',
  'day': 'Monday and Wednesday',
  'department': 'CMET',
  'instructor_first_name': 'Todd',
  'instructor_last_name': 'Sanders',
  'room_number': '107',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '11850',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET211',
  'course_title': 'Environmental Quality',
  'day': 'Tuesday',
  'department': 'CMET',
  'instructor_first_name': 'Todd',
  'instructor_last_name': 'Sanders',
  'room_number': '105',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '13856',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET211',
  'course_title': 'Environmental Quality',
  'day': 'Monday',
  'department': 'CMET',
  'instructor_first_name': 'Todd',
  'instructor_last_name': 'Sanders',
  'room_number': '105',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '13856',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET211',
  'course_title': 'Environmental Quality',
  'day': 'Monday and Wednesday',
  'department': 'CMET',
  'instructor_first_name': 'Todd',
  'instructor_last_name': 'Sanders',
  'room_number': '107',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '11859',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'CMET212',
  'course_title': 'Thermodynamics I',
  'day': 'Tuesday and Thursday',
  'department': 'CMET',
  'instructor_first_name': 'Greg',
  'instructor_last_name': 'Gerstner',
  'room_number': '104',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '11859',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'CMET212',
  'course_title': 'Thermodynamics I',
  'day': 'Friday',
  'department': 'CMET',
  'instructor_first_name': 'Greg',
  'instructor_last_name': 'Gerstner',
  'room_number': '104',
  'start_time': '1:00pm',
  'stop_time': '2:50pm'},
 {'CRN': '10266',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'CMET228',
  'course_title': 'Construction Materials',
  'day': 'Tuesday',
  'department': 'CMET',
  'instructor_first_name': 'Tara',
  'instructor_last_name': 'Nelson',
  'room_number': '104',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10266',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET228',
  'course_title': 'Construction Materials',
  'day': 'Thursday',
  'department': 'CMET',
  'instructor_first_name': 'Tara',
  'instructor_last_name': 'Nelson',
  'room_number': '105',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10429',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET241',
  'course_title': 'Structural Steel Drafting',
  'day': 'Tuesday and Thursday',
  'department': 'CMET',
  'instructor_first_name': 'William',
  'instructor_last_name': 'Eisenhauer',
  'room_number': '106',
  'start_time': '4:00pm',
  'stop_time': '7:20pm'},
 {'CRN': '14428',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET255',
  'course_title': 'Civil & Mech. Prof Skill I',
  'day': 'Wednesday',
  'department': 'CMET',
  'instructor_first_name': 'Tara',
  'instructor_last_name': 'Nelson',
  'room_number': '112',
  'start_time': '3:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '14428',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'CMET255',
  'course_title': 'Civil & Mech. Prof Skill I',
  'day': 'Wednesday',
  'department': 'CMET',
  'instructor_first_name': 'Tara',
  'instructor_last_name': 'Nelson',
  'room_number': '112',
  'start_time': '1:00pm',
  'stop_time': '2:50pm'},
 {'CRN': '15906',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET101A',
  'course_title': 'Elect. Lab Skills and Equip. 1',
  'day': 'Friday',
  'department': 'EETA',
  'instructor_first_name': 'Trung',
  'instructor_last_name': 'Le',
  'room_number': '313',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '15996',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET101A',
  'course_title': 'Elect. Lab Skills and Equip. 1',
  'day': 'Friday',
  'department': 'EETA',
  'instructor_first_name': 'Larry',
  'instructor_last_name': 'Lam',
  'room_number': '316',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '15689',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET101B',
  'course_title': 'Elect. Lab Skills and Equip. 2',
  'day': 'Monday',
  'department': 'EETB',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Goldman',
  'room_number': '315',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '15690',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET101B',
  'course_title': 'Elect. Lab Skills and Equip. 2',
  'day': 'Monday',
  'department': 'EETB',
  'instructor_first_name': 'Richard',
  'instructor_last_name': 'Fesler',
  'room_number': '313',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10631',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'EET111',
  'course_title': 'Elec Circuit Analysis I',
  'day': 'Monday',
  'department': 'EET',
  'instructor_first_name': 'Yunhui',
  'instructor_last_name': 'Chu',
  'room_number': '122',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '10631',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'EET111',
  'course_title': 'Elec Circuit Analysis I',
  'day': 'Tuesday',
  'department': 'EET',
  'instructor_first_name': 'Yunhui',
  'instructor_last_name': 'Chu',
  'room_number': '122',
  'start_time': '6:00pm',
  'stop_time': '6:50pm'},
 {'CRN': '16265',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET111',
  'course_title': 'Elec Circuit Analysis I',
  'day': 'Tuesday',
  'department': 'EET',
  'instructor_first_name': 'Corneliu',
  'instructor_last_name': 'Boghean',
  'room_number': '316',
  'start_time': '7:00pm',
  'stop_time': '9:50pm'},
 {'CRN': '16272',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET111',
  'course_title': 'Elec Circuit Analysis I',
  'day': 'Tuesday',
  'department': 'EET',
  'instructor_first_name': 'Yunhui',
  'instructor_last_name': 'Chu',
  'room_number': '313',
  'start_time': '7:00pm',
  'stop_time': '9:50pm'},
 {'CRN': '11036',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'EET112',
  'course_title': 'Elec Circuit Analysis II',
  'day': 'Monday and Wednesday',
  'department': 'EET',
  'instructor_first_name': 'Sanda',
  'instructor_last_name': 'Williams',
  'room_number': '103',
  'start_time': '1:00pm',
  'stop_time': '2:50pm'},
 {'CRN': '16267',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET112',
  'course_title': 'Elec Circuit Analysis II',
  'day': 'Tuesday',
  'department': 'EET',
  'instructor_first_name': 'Sanda',
  'instructor_last_name': 'Williams',
  'room_number': '313',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10632',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'EET121',
  'course_title': 'Digital Systems 1',
  'day': 'Wednesday',
  'department': 'EET',
  'instructor_first_name': 'Scott',
  'instructor_last_name': 'Lowrey',
  'room_number': '122',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '18022',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'EET121',
  'course_title': 'Digital Systems 1',
  'day': 'Wednesday',
  'department': 'EET',
  'instructor_first_name': 'Spencer',
  'instructor_last_name': 'Poff',
  'room_number': '126',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '16268',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET121',
  'course_title': 'Digital Systems 1',
  'day': 'Thursday',
  'department': 'EET',
  'instructor_first_name': 'Scott',
  'instructor_last_name': 'Lowrey',
  'room_number': '313',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '17002',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET121',
  'course_title': 'Digital Systems 1',
  'day': 'Thursday',
  'department': 'EET',
  'instructor_first_name': 'Joe',
  'instructor_last_name': 'Schoelen',
  'room_number': '316',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '11429',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'EET122',
  'course_title': 'Digital Systems 2',
  'day': 'Tuesday and Thursday',
  'department': 'EET',
  'instructor_first_name': 'Ray',
  'instructor_last_name': 'Schmelzer',
  'room_number': '204',
  'start_time': '1:00pm',
  'stop_time': '2:50pm'},
 {'CRN': '11430',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'EET122',
  'course_title': 'Digital Systems 2',
  'day': 'Tuesday and Thursday',
  'department': 'EET',
  'instructor_first_name': 'Scott',
  'instructor_last_name': 'Lowrey',
  'room_number': '112',
  'start_time': '1:00pm',
  'stop_time': '2:50pm'},
 {'CRN': '16269',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET122',
  'course_title': 'Digital Systems 2',
  'day': 'Thursday',
  'department': 'EET',
  'instructor_first_name': 'Ray',
  'instructor_last_name': 'Schmelzer',
  'room_number': '313',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '16270',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET122',
  'course_title': 'Digital Systems 2',
  'day': 'Thursday',
  'department': 'EET',
  'instructor_first_name': 'Scott',
  'instructor_last_name': 'Lowrey',
  'room_number': '316',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10480',
  'building': '',
  'campus': 'We',
  'course_num': 'EET188',
  'course_title': 'Industrial Safety',
  'day': ' from',
  'department': 'EET',
  'instructor_first_name': 'Sanda',
  'instructor_last_name': 'Williams',
  'room_number': 'Web',
  'start_time': '—\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n from',
  'stop_time': '—\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n from'},
 {'CRN': '10633',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'EET222',
  'course_title': 'Operational Amplifier Circuits',
  'day': 'Tuesday and Thursday',
  'department': 'EET',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '126',
  'start_time': '1:00pm',
  'stop_time': '2:50pm'},
 {'CRN': '11248',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET222',
  'course_title': 'Operational Amplifier Circuits',
  'day': 'Tuesday',
  'department': 'EET',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '315',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '11248',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET222',
  'course_title': 'Operational Amplifier Circuits',
  'day': 'Thursday',
  'department': 'EET',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '315',
  'start_time': '6:00pm',
  'stop_time': '6:50pm'},
 {'CRN': '16273',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET222',
  'course_title': 'Operational Amplifier Circuits',
  'day': 'Tuesday',
  'department': 'EET',
  'instructor_first_name': 'Scott',
  'instructor_last_name': 'Lowrey',
  'room_number': '316',
  'start_time': '3:00pm',
  'stop_time': '5:50pm'},
 {'CRN': '16274',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET222',
  'course_title': 'Operational Amplifier Circuits',
  'day': 'Thursday',
  'department': 'EET',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '315',
  'start_time': '7:00pm',
  'stop_time': '9:50pm'},
 {'CRN': '17022',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET241',
  'course_title': 'Programming for Electronics',
  'day': 'Monday',
  'department': 'EET',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Smith',
  'room_number': '313',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '16264',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET241',
  'course_title': 'Programming for Electronics',
  'day': 'Wednesday',
  'department': 'EET',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Smith',
  'room_number': '313',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '10866',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET261',
  'course_title': 'Biomedical Equipment II',
  'day': 'Monday',
  'department': 'EET',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': '316',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '16263',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET261',
  'course_title': 'Biomedical Equipment II',
  'day': 'Monday',
  'department': 'EET',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': '316',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '15726',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET263',
  'course_title': 'Electronic Control Systems 1',
  'day': 'Friday',
  'department': 'EET',
  'instructor_first_name': 'Ray',
  'instructor_last_name': 'Schmelzer',
  'room_number': '315',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '15726',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET263',
  'course_title': 'Electronic Control Systems 1',
  'day': 'Friday',
  'department': 'EET',
  'instructor_first_name': 'Ray',
  'instructor_last_name': 'Schmelzer',
  'room_number': '315',
  'start_time': '3:00pm',
  'stop_time': '4:50pm'},
 {'CRN': '11294',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET280A',
  'course_title': 'CE:Electronic Engineering Tech',
  'day': ' from',
  'department': 'EETA',
  'instructor_first_name': 'Linda',
  'instructor_last_name': 'Browning',
  'room_number': '200',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '15923',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET280A',
  'course_title': 'CE:Electronic Engineering Tech',
  'day': ' from',
  'department': 'EETA',
  'instructor_first_name': 'Linda',
  'instructor_last_name': 'Browning',
  'room_number': '200',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '11895',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET280C',
  'course_title': 'CE: BMET Practicum',
  'day': ' from',
  'department': 'EETC',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': '200',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '11984',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET280C',
  'course_title': 'CE: BMET Practicum',
  'day': ' from',
  'department': 'EETC',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': '200',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '11985',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'EET280C',
  'course_title': 'CE: BMET Practicum',
  'day': ' from',
  'department': 'EETC',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': '200',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '18030',
  'building': '',
  'campus': 'We',
  'course_num': 'EET280C',
  'course_title': 'CE: BMET Practicum',
  'day': ' from',
  'department': 'EETC',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': 'Web',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '18031',
  'building': '',
  'campus': 'We',
  'course_num': 'EET280C',
  'course_title': 'CE: BMET Practicum',
  'day': ' from',
  'department': 'EETC',
  'instructor_first_name': 'Chuck',
  'instructor_last_name': 'Fenning',
  'room_number': 'Web',
  'start_time': 'TBA\nTo Be Announced\n\n from',
  'stop_time': 'TBA\nTo Be Announced\n\n from'},
 {'CRN': '10471',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR100',
  'course_title': 'Exploring Engineering',
  'day': 'Friday',
  'department': 'ENGR',
  'instructor_first_name': 'Scott',
  'instructor_last_name': 'Lowrey',
  'room_number': '125',
  'start_time': '9:00am',
  'stop_time': '9:50am'},
 {'CRN': '10470',
  'building': '',
  'campus': 'We',
  'course_num': 'ENGR100',
  'course_title': 'Exploring Engineering',
  'day': ' from',
  'department': 'ENGR',
  'instructor_first_name': 'Instructor:',
  'instructor_last_name': 'Instructor:',
  'room_number': 'Web',
  'start_time': '—\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n from',
  'stop_time': '—\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n from'},
 {'CRN': '10708',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR101',
  'course_title': 'Engineering Fundamentals',
  'day': 'Friday',
  'department': 'ENGR',
  'instructor_first_name': 'Todd',
  'instructor_last_name': 'Sanders',
  'room_number': '106',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '10708',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR101',
  'course_title': 'Engineering Fundamentals',
  'day': 'Friday',
  'department': 'ENGR',
  'instructor_first_name': 'Greg',
  'instructor_last_name': 'Gerstner',
  'room_number': '103',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10709',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR101',
  'course_title': 'Engineering Fundamentals',
  'day': 'Monday',
  'department': 'ENGR',
  'instructor_first_name': 'Peter',
  'instructor_last_name': 'Kazarinoff',
  'room_number': '125',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '10709',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR101',
  'course_title': 'Engineering Fundamentals',
  'day': 'Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Greg',
  'instructor_last_name': 'Gerstner',
  'room_number': '107',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '13221',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR101',
  'course_title': 'Engineering Fundamentals',
  'day': 'Tuesday',
  'department': 'ENGR',
  'instructor_first_name': 'Jenna',
  'instructor_last_name': 'Bell',
  'room_number': '125',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '13221',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR101',
  'course_title': 'Engineering Fundamentals',
  'day': 'Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'Jenna',
  'instructor_last_name': 'Bell',
  'room_number': '107',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '15727',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR102',
  'course_title': 'Engineering Graphics',
  'day': 'Monday and Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Catherine',
  'instructor_last_name': 'Stark',
  'room_number': '107',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '13941',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR105',
  'course_title': 'ENG. Graph. 3-D',
  'day': 'Monday and Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Adam',
  'instructor_last_name': 'Scheible',
  'room_number': '106',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '13939',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR114',
  'course_title': 'Engineering Programming',
  'day': 'Monday and Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Rekha',
  'instructor_last_name': 'Rao',
  'room_number': '106',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '14054',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR114',
  'course_title': 'Engineering Programming',
  'day': 'Monday and Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Peter',
  'instructor_last_name': 'Kazarinoff',
  'room_number': '106',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '10753',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'ENGR171',
  'course_title': 'Intro to Digital Logic Design',
  'day': 'Tuesday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Goldman',
  'room_number': '315',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '10753',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR171',
  'course_title': 'Intro to Digital Logic Design',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Goldman',
  'room_number': '103',
  'start_time': '8:00am',
  'stop_time': '9:50am'},
 {'CRN': '12602',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR171',
  'course_title': 'Intro to Digital Logic Design',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Goldman',
  'room_number': '103',
  'start_time': '8:00am',
  'stop_time': '9:50am'},
 {'CRN': '12602',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'ENGR171',
  'course_title': 'Intro to Digital Logic Design',
  'day': 'Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Goldman',
  'room_number': '315',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '10472',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR211',
  'course_title': 'Statics',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'William',
  'instructor_last_name': 'Eisenhauer',
  'room_number': '122',
  'start_time': '1:00pm',
  'stop_time': '3:20pm'},
 {'CRN': '14626',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR211',
  'course_title': 'Statics',
  'day': 'Monday and Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Jenna',
  'instructor_last_name': 'Bell',
  'room_number': '104',
  'start_time': '6:00pm',
  'stop_time': '8:20pm'},
 {'CRN': '10473',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR212',
  'course_title': 'Dynamics',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'Jenna',
  'instructor_last_name': 'Bell',
  'room_number': '103',
  'start_time': '1:00pm',
  'stop_time': '3:20pm'},
 {'CRN': '10857',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR212',
  'course_title': 'Dynamics',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'Mark',
  'instructor_last_name': 'Brazier',
  'room_number': '104',
  'start_time': '6:00pm',
  'stop_time': '8:20pm'},
 {'CRN': '10474',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR221',
  'course_title': 'Electrical Circuits I',
  'day': 'Monday',
  'department': 'ENGR',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '103',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '10474',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'ENGR221',
  'course_title': 'Electrical Circuits I',
  'day': 'Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Curtis',
  'instructor_last_name': 'Lipski',
  'room_number': '315',
  'start_time': '7:00pm',
  'stop_time': '9:50pm'},
 {'CRN': '10474',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR221',
  'course_title': 'Electrical Circuits I',
  'day': 'Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '103',
  'start_time': '6:00pm',
  'stop_time': '6:50pm'},
 {'CRN': '12576',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR221',
  'course_title': 'Electrical Circuits I',
  'day': 'Monday',
  'department': 'ENGR',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '103',
  'start_time': '6:00pm',
  'stop_time': '8:50pm'},
 {'CRN': '12576',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR221',
  'course_title': 'Electrical Circuits I',
  'day': 'Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Dan',
  'instructor_last_name': 'Kruger',
  'room_number': '103',
  'start_time': '6:00pm',
  'stop_time': '6:50pm'},
 {'CRN': '12576',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'ENGR221',
  'course_title': 'Electrical Circuits I',
  'day': 'Wednesday',
  'department': 'ENGR',
  'instructor_first_name': 'Ray',
  'instructor_last_name': 'Schmelzer',
  'room_number': '316',
  'start_time': '7:00pm',
  'stop_time': '9:50pm'},
 {'CRN': '10475',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR222',
  'course_title': 'Electrical Circuits II',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Smith',
  'room_number': '103',
  'start_time': '10:00am',
  'stop_time': '11:50am'},
 {'CRN': '10475',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'ENGR222',
  'course_title': 'Electrical Circuits II',
  'day': 'Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'Steve',
  'instructor_last_name': 'Haskell',
  'room_number': '313',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '13223',
  'building': 'ST ',
  'campus': 'SY',
  'course_num': 'ENGR222',
  'course_title': 'Electrical Circuits II',
  'day': 'Tuesday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Smith',
  'room_number': '313',
  'start_time': '1:00pm',
  'stop_time': '3:50pm'},
 {'CRN': '13223',
  'building': 'SS ',
  'campus': 'SY',
  'course_num': 'ENGR222',
  'course_title': 'Electrical Circuits II',
  'day': 'Tuesday and Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'David',
  'instructor_last_name': 'Smith',
  'room_number': '103',
  'start_time': '10:00am',
  'stop_time': '11:50am'},
 {'CRN': '13231',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR262',
  'course_title': 'Manufacturing Processes',
  'day': 'Thursday',
  'department': 'ENGR',
  'instructor_first_name': 'Peter',
  'instructor_last_name': 'Kazarinoff',
  'room_number': '112',
  'start_time': '9:00am',
  'stop_time': '11:50am'},
 {'CRN': '13231',
  'building': 'AM ',
  'campus': 'SY',
  'course_num': 'ENGR262',
  'course_title': 'Manufacturing Processes',
  'day': 'Friday',
  'department': 'ENGR',
  'instructor_first_name': 'Peter',
  'instructor_last_name': 'Kazarinoff',
  'room_number': '101',
  'start_time': '9:00am',
  'stop_time': '11:50am'}]

def main():
    pprint(d)

if __name__ == "__main__":
    main()
